=== clarin-eric/switchboard-tool-registry/schemas/spec-v2.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://switchboard.clarin.eu/tool-spec-v2.json",
    "title": "JSON Schema for the Switchboard tool specification v.2",
    "type": "object",
    "items": null,
    "required": [
        "formatVersion",
        "id",
        "task",
        "deployment",
        "integrationType",
        "name",
        "description",
        "logo",
        "homepage",
        "creators",
        "contact",
        "inputs"
    ],
    "additionalProperties": false,
    "properties": {
        "formatVersion": {
            "type": "string",
            "enum": ["2"]
        },
        "id": {
            "type": "integer"
        },
        "task": {
            "type": "string",
            "title": "Task description",
            "enum": [
                "Constituency Parsing",
                "Coreference Resolution",
                "Data Conversion",
                "Dependency Parsing",
                "Distant Reading",
                "Editing",
                "Extraction of Polish terminology",
                "Grapheme to Phoneme Conversion",
                "Handwritten Text Recognition",
                "Hyphenation",
                "Inclusion detection",
                "Keyword Extractor",
                "Lemmatization",
                "Lookup Tools",
                "Machine Translation",
                "Metadata Processing",
                "Morpho-syntactic tagger",
                "Morphological Analysis",
                "N-Gramming",
                "Named Entity Recognition",
                "Named Entity Relation Detection",
                "NLP suite for Dutch",
                "Optical Character Recognition",
                "Part-Of-Speech Tagging",
                "Relation between name entities detection",
                "Sentiment Analysis",
                "Shallow Parsing",
                "Spatial expression detection",
                "Speech Recognition",
                "Speech segmentation",
                "Speech transcription",
                "Spelling correction",
                "Stylometry",
                "Text Analytics",
                "Text Enhancement",
                "Text Normalisation",
                "Text Summarization",
                "TF, IDF, TF-IDF calculation",
                "Tokenisation",
                "Topic Modelling",
                "Transliteration",
                "Visualisation of 3D models",
                "Visualisation of Geographic Data",
                "Word sense disambiguation"
            ]
        },
        "deployment": {
            "type": "string",
            "title": "Deployment type",
            "default": "development",
            "enum": ["production", "development"]
        },
        "integrationType": {
            "type": "string",
            "title": "Integration with Switchboard",
            "description": "Integration level: Integrated (fully integrated), External (some parameters must be supplied by the user) and Local (download and install the application locally)",
            "default": "Integrated",
            "enum": ["Integrated", "External", "Local"]
        },
        "name": {
            "title": "Tool name",
            "type": "string"
        },
        "description": {
            "type": "string",
            "title": "Tool's description"
        },
        "logo": {
            "type": "string",
            "title": "The tool's logo file name",
            "examples": ["mylogo.jpg"]
        },
        "homepage": {
            "type": "string",
            "format": "uri",
            "title": "Homepage",
            "examples": ["https://example.com"]
        },
        "keywords": {
            "type": "array",
            "title": "Keywords",
            "items": {"type": "string"}
        },
        "creators": {
            "type": "string",
            "title": "Tool's creators"
        },
        "contact": {
            "type": "object",
            "title": "The Contact Schema",
            "properties": {
                "person": {
                    "type": "string",
                    "title": "Person name"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "title": "Email"
                },
                "url": {
                    "type": "string",
                    "format": "uri",
                    "title": "Contact Page Link"
                }
            },
            "additionalProperties": false
        },
        "location": {
             "type": "string",
            "title": "Geographical location",
            "examples": ["Tuebingen, Germany"]
        },
        "authentication": {
            "type": ["string", "null"],
            "title": "Authentication mechanism description, or null",
            "default": null
        },
        "inputs": {
            "type": "array",
            "title": "Input specs",
            "items": {"$ref": "#/definitions/input_entry"}
        },
        "batchProcessing": {
            "type": "object",
            "title": "Batch processing",
            "properties": {
                "mode": {"type": "string", "enum": ["zip"]},
                "queryParameters": {
                    "type": "array",
                    "title": "Batch mode query parameters",
                    "items": {"$ref": "#/definitions/service_param"}
                }
            }
        },
        "webApplication": {},
        "standaloneApplication": {},
        "usageRestrictions": {
            "type": "object",
            "title": "Usage Restrictions",
            "properties": {
                "individualUserRestrictions": {
                    "type": "string",
                    "enum": ["academic", "public", "regional", "other", "unknown", "license only"]
                },
                "countriesNotSupported": {"type": "string"},
                "countriesSupported": {"type": "string"}
            },
            "additionalProperties": false
        }
    },
    "allOf": [
        {
            "if": {"properties": {"integrationType": {"const": "Local"}}},
            "then": {"properties": {"standaloneApplication": {"$ref": "#/definitions/standalone_application"}}}
        },
        {
            "if": {"properties": {"integrationType": {"const": "Integrated"}}},
            "then": {"properties": {"webApplication": {"$ref": "#/definitions/web_application"}}}
        },
        {
            "if": {"properties": {"integrationType": {"const": "External"}}},
            "then": {"properties": {"webApplication": {
                "allOf": [
                    {"$ref": "#/definitions/web_application"},
                    {"$ref": "#/definitions/with_manual_args"}
                ]}}}
        }
    ],
    "definitions": {
        "web_application": {
            "$id": "#web_application",
            "type": "object",
            "title": "Web Application",
            "properties": {
                "browserRequirements": {"type": "string"},
                "applicationSuite": {"type": "string"},
                "scalabilityType": {
                    "type": "string",
                    "enum": ["singleUser", "smallGroups", "classroomSize", "lectureSize", "unlimited", "unknown", "other"]
                },
                "licenseInformation": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "runtimeInformation": {"$ref": "#/definitions/runtime_information"},
                "url": {
                    "type": "string",
                    "format": "uri",
                    "title": "Tool's URL",
                    "examples": ["https://weblicht.sfs.uni-tuebingen.de/weblicht/"]
                },
                "queryParameters": {
                    "type": "array",
                    "title": "Query parameter list",
                    "items": {"$ref": "#/definitions/service_param"}
                },
                "pathParameters": {
                    "type": "array",
                    "title": "Path parameter list",
                    "items": {"$ref": "#/definitions/service_param"}
                }
            }
        },
        "with_manual_args": {
            "$id": "#with_manual_args",
            "type": "object",
            "title": "Application with manual arguments",
            "properties": {
                "manualParameters": {
                    "type": "array",
                    "title": "Manual parameter list",
                    "items": {"$ref": "#/definitions/service_param"}
                }
            }
        },
        "standalone_application": {
            "$id": "#standalone_application",
            "type": "object",
            "title": "Standalone Application",
            "properties": {
                "availableOnDevice": {
                    "type":"array",
                    "items": {"type": "string"}
                },
                "installURL" : {
                    "type":"array",
                    "items": {"type": "string"}
                },
                "downloadURL" : {
                    "type":"array",
                    "items": {
                        "type": "object",
                        "required": ["type", "url"],
                        "properties": {
                            "type": {"type": "string"},
                            "targetlang": {"$ref": "#/definitions/language_code"},
                            "url": {"type": "string", "format": "uri"},
                            "additionalProperties": false
                        }
                    }
                },
                "applicationSuite": {"type": "string"},
                "featureList": {"type": "string"},
                "permissions": {"type": "string"},
                "releaseNotes": {"type": "string"},
                "softwareAddOn": {"type": "string"},
                "softwareRequirements": {"type": "string"},
                "supportingData": {"type": "string"},
                "dataTransfer": {
                    "type": "string",
                    "enum": ["none", "local", "cloud", "unknown", "other", "N/A"]
                },
                "licenseInformation": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "runtimeInformation": {"$ref": "#/definitions/runtime_information"}
            },
            "additionalProperties": false
        },
        "runtime_information": {
            "$id": "#runtime_information",
            "type": "object",
            "title": "Runtime Information",
            "properties": {
                "memoryRequirements": {"type": "string"},
                "storageRequirements": {"type": "string"},
                "processorRequirements": {"type": "string"},
                "operatingSystem": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {"type": "string"},
                            "versionFrom": {"type": "string"},
                            "versionTo": {"type": "string"}
                        },
                        "additionalProperties": false
                    }
                },
                "fileSize": {"type": "string"},
                "installationLicense": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "runtimeEnvironment": {
                    "type": "array",
                    "items": {"type": "string"}
                }
            },
            "additionalProperties": false
        },
        "service_param": {
            "$id": "#service_param",
            "type": "object",
            "title": "Parameter",
            "properties": {
                "name": {"type": "string"},
                "bind": {"type": "string"},
                "value": {"type": "string"},
                "encoding": {"type": "string"}
            },
            "required": ["name"],
            "additionalProperties": false
        },
        "mimetype_list": {
            "$id": "#mimetype_list",
            "type": "array",
            "title": "Mediatype list",
            "minItems": 1,
            "items": {
                "type": "string",
                "title": "Mediatype",
                "examples": [
                    "text/plain",
                    "text/rtf",
                    "application/pdf",
                    "application/msword"
                ]
            }
        },
        "input_entry": {
            "$id": "#input_entry",
            "type": "object",
            "title": "Input entry",
            "properties": {
                "id": {"type": "string"},
                "name": {"type": "string"},
                "mediatypes": {"$ref": "#/definitions/mimetype_list"},
                "languages": {"oneOf": [
                    {"type": "string"},
                    {"type":"array", "items": {"$ref": "#/definitions/language_code_3"}}
                ]},
                "maxSize": {"type": "integer"},
                "multiple": {"type": "boolean"},
                "optional": {"type": "boolean"}
            },
            "additionalProperties": false
        },
        "language_code_3": {
            "type": "string",
            "title": "Language Identifier, ISO 693-3",
            "default": "eng",
            "examples": ["eng", "deu"],
            "pattern": "^(.{3})$"
        },
        "language_code": {
            "type": "string",
            "title": "Language Identifier, ISO 693-3",
            "default": "eng",
            "examples": ["eng", "deu"],
            "pattern": "^(.{2,3})$"
        }
    }
}

=== clarin-eric/switchboard-tool-registry/tools/spaCy monolingual NER.json
{
	"formatVersion": "2",
    "id": 122122,
    "task": "Named Entity Recognition",
    "deployment": "production",
    "integrationType" : "Integrated",
    "name": "spaCy monolingual NER",
    "logo": "It-Sr-NER-logo-small.png",
    "homepage": "https://github.com/rankastankovic/It-Sr-NER",
    "location": "Belgrade, Serbia",
    "creators": "Universit√† degli studi di Torino",
    "contact": {
        "person": "Olja Perisic",
        "email": "olja.perisic@unito.it"
    },
    "authentication": "no",
    "description": "NER web service for monolingual texts and files (txt).",
    
    "webApplication" : {
		"url": "https://ners.jerteh.rs/api",
    	"queryParameters": [{
			"name": "lng",
			"bind": "file/language",
			"encoding": "639-1"
        }, { 
          		"name": "feat",
			"value": "ner"
       	}, {
          		"name": "data",
			"bind": "file/dataurl",
			"encoding": "639-1"
        }]
          
       
    },
    

     "inputs" : [{
        "id": "file",
        "mediatypes": ["text/plain"],
        "languages": ["cat", "zho", "hrv", "dan",  "nld", "eng", "fin", "fra", "deu", "ell", "ita", "jpn", "kor", "lit", "mkd", "nob", "pol", "por", "ron", "rus", "spa", "swe", "ukr", "srp"]
     }]
      
}

=== clarin-eric/switchboard-tool-registry/tools/spaCy monolingual NER and Geoparsing.json
{
	"formatVersion": "2",
    "id": 122124,
    "task": "Named Entity Recognition",
    "deployment": "production",
    "integrationType" : "Integrated",
    "name": "spaCy monolingual NER and Geoparsing",
    "logo": "It-Sr-NER-logo-small.png",
    "homepage": "https://github.com/rankastankovic/It-Sr-NER",
    "location": "Belgrade, Serbia",
    "creators": "Universit√† degli studi di Torino",
    "contact": {
        "person": "Olja Perisic",
        "email": "olja.perisic@unito.it"
    },
    "authentication": "no",
    "description": "NER and Geoparsing web service for monolingual texts and files (txt). Service finds location-related named entities and pin them on a map.",
    
    "webApplication" : {
		"url": "https://ners.jerteh.rs/api",
    	"queryParameters": [{
			"name": "lng",
			"bind": "file/language",
			"encoding": "639-1"
        }, { 
          		"name": "feat",
			"value": "geo"
       	}, {
          		"name": "data",
			"bind": "file/dataurl",
			"encoding": "639-1"
        }]
          
       
    },
    

     "inputs" : [{
        "id": "file",
        "mediatypes": ["text/plain"],
        "languages": ["cat", "zho", "hrv", "dan",  "nld", "eng", "fin", "fra", "deu", "ell", "ita", "jpn", "kor", "lit", "mkd", "nob", "pol", "por", "ron", "rus", "spa", "swe", "ukr", "srp"]
     }]
      
}

=== clarin-eric/switchboard-tool-registry/tools/Postagger.json
{
    "formatVersion": "2",
    "id": 182,
    "task": "Part-Of-Speech Tagging",
    "deployment": "production",
    "integrationType": "Integrated",
    "name": "Postagger",
    "description": "Set of tools used in natural language processing to assign labels or tags to text elements such as words or tokens. Postagger works at the stage after the text has been analyzed by a morphological or syntactic tagger and is intended to make the final classification and assign appropriate labels to individual text elements.",
    "logo": "clarin-pl.png",
    "homepage": "https://services.clarin-pl.eu/services/postagger",
    "creators": "Clarin-PL",
    "contact": {
        "person": "Tomasz Walkowiak",
        "email": "tomasz.walkowiak@pwr.edu.pl"
    },
    "keywords": ["postagger", "nlp", "natural language processing", "text analysis", "morphological tagger", "syntactic tagger"],
    "location": "Wroclaw, Poland",
    "authentication": "Yes, user should create an account on the Clarin-PL website",
    "inputs": [{
        "id": "text",
        "mediatypes": ["application/zip"],
        "languages": ["eng", "pol"]
    }],
    "webApplication": {
        "url": "https://services.clarin-pl.eu/services/postagger/creator",
        "queryParameters": [{
            "name": "weblicht-input",
            "bind": "text/dataurl"
        }]
    }
}

=== clarin-eric/switchboard-tool-registry/tools/texton-lemmas.json
{
    "formatVersion": "2",
    "id": 222,
    "task": "Lemmatization",
    "deployment": "production",
    "integrationType": "Integrated",
    "name": "Text Tonsorium - Lemmas.",
    "description": "The Text Tonsorium designs and enacts workflows that fulfil your goal. Here, the goal is set to \"lemmatization of the input\". Once in Text Tonsorium, you can refine or change the goal.",
    "logo": "texton.png",
    "homepage": "https://cst.dk/texton/help",
    "creators": "CLARIN B-centre at the University of Copenhagen, Denmark",
    "contact": {
        "person": "Bart Jongejan",
        "email": "bartj@hum.ku.dk"
    },
    "keywords": [ "lemmatization", "lemmatisation", "TEI P5", "CONLL", "HTML", "JSON", "PDF", "Word", "contemporary", "late modern", "medieval", "OCR", "fraktur", "Danish" ],
    "location": "Copenhagen, Denmark",
    "authentication": "no",
    "inputs": [
        {
            "id": "text",
            "mediatypes": [
                "application/pdf",
                "application/vnd.ms-powerpoint",
                "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                "application/vnd.oasis.opendocument.presentation",
                "application/vnd.ms-excel",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.shee",
                "application/vnd.oasis.opendocument.spreadsheet",
                "application/x-download",
                "application/octet-stream",
                "application/msword",
                "application/vnd.oasis.opendocument.text",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "application/json",
                "application/tei+xml",
                "application/rtf",
                "application/xhtml+xml",
                "image/gif",
                "image/jpeg",
                "image/pjpeg",
                "image/png",
                "image/tiff",
                "image/vnd.microsoft.icon",
                "image/svg+xml",
                "text/html",
                "text/plain",
                "text/rtf",
                "text/x-conll",
                "text/xml"
            ],
            "languages": [ "afr", "ast", "bel", "bul", "cat", "ces", "cym", "dan", "deu", "ell", "eng", "est", "fao", "fas", "fra", "gla", "gle", "glg", "glv", "gml", "hrv", "hun", "isl", "ita", "kat", "lat", "mkd", "nld", "nor", "pol", "por", "ron", "rus", "slk", "slv", "spa", "sqi", "srp", "swe", "ukr" ],
            "maxSize": 40960000,
            "multiple": true
        }
    ],
    "webApplication": {
        "url": "https://cst.dk/texton/specifyGoal",
        "queryParameters": [
            {
                "name": "URLS",
                "bind": "text/dataurl"
            },
            {
                "name": "Ilang",
                "bind": "text/language",
                "encoding": "639-3"
            },
            {
                "name": "Olang",
                "bind": "text/language",
                "encoding": "639-3"
            },
            {
                "name": "UIlanguage",
                "value": "en"
            },
            {
                "name": "Ifacet",
                "value": "txt"
            },
            {
                "name": "Iambig",
                "value": "una"
            },
            {
                "name": "Iapp",
                "value": "nrm"
            },
            {
                "name": "Ofacet",
                "value": "lem"
            },
            {
                "name": "Operiod",
                "value": "c21"
            },
            {
                "name": "Opres",
                "value": "nml"
            }
        ]
    }
}

=== clarin-eric/switchboard-tool-registry/tools/Topic.json
{
    "formatVersion": "2",
    "id": 104,
    "task": "Topic Modelling",
    "deployment": "production",
    "integrationType": "Integrated",
    "name": "Topic",
    "description": "A service for automatically extracting information about what topics are covered in the texts. It uses topic modeling (LDA), which detects topics based on the co-occurrence of words in one document. The service assigns each document to several topics. The detected topic represents what a list of pairs: the word and the probability of its occurrence in the topic. It enables qualitative (detection of non-obvious topics) and quantitative analysis of processed texts.",
    "logo": "clarin-pl.png",
    "homepage": "https://services.clarin-pl.eu/applications/topic",
    "creators": "Clarin-PL",
    "contact": {
        "person": "Tomasz Walkowiak",
        "email": "tomasz.walkowiak@pwr.edu.pl"
    },
    "keywords": ["topic", "topic modelling", "LDA", "text analysis"],
    "location": "Wroclaw, Poland",
    "authentication": "Yes, user should create an account on the Clarin-PL website",
    "inputs": [{
        "id": "text",
        "mediatypes": ["application/zip"],
        "languages": ["eng", "pol"]
    }],
    "webApplication": {
        "url": "https://services.clarin-pl.eu/tools/en/topic/app/new",
        "queryParameters": [{
            "name": "weblicht-input",
            "bind": "text/dataurl"
        }]
    }
}

=== clarin-eric/switchboard-tool-registry/tools/spaCy bilingual NER and NEL.json
{
	"formatVersion": "2",
    "id": 122125,
    "task": "Named Entity Recognition",
    "deployment": "production",
    "integrationType" : "Integrated",
    "name": "spaCy binlingual NER and NEL (for TMX)",
    "logo": "It-Sr-NER-logo-small.png",
    "homepage": "https://github.com/rankastankovic/It-Sr-NER",
    "location": "Belgrade, Serbia",
    "creators": "Universit√† degli studi di Torino",
    "contact": {
        "person": "Olja Perisic",
        "email": "olja.perisic@unito.it"
    },
    "authentication": "no",
    "description": "NER and NEL web service for bilingual (tmx) files.",
    
    "webApplication" : {
		"url": "https://ners.jerteh.rs/api",
    	"queryParameters": [{ 
          		"name": "feat",
			"value": "nernel"
       	}, {
          		"name": "data",
			"bind": "file/dataurl",
			"encoding": "639-1"
        }]
          
       
    },
    

     "inputs" : [{
        "id": "file",
        "mediatypes": ["application/xml"] }]
      
}

=== clarin-eric/switchboard-tool-registry/tools/Punctator.json
{
    "formatVersion": "2",
    "id": 55,
    "task": "Text Enhancement",
    "deployment": "production",
    "integrationType": "Integrated",
    "name": "Punctuator",
    "description": "Unlike simple tools built into word processors, this tool applies context-sensitive spelling rules rather than placing characters mechanically. It adds not only punctuation marks, but also dots after ordinal numbers and parentheses around parentheses.",
    "logo": "clarin-pl.png",
    "homepage": "https://services.clarin-pl.eu/services/punctuator-premium",
    "creators": "Clarin-PL",
    "contact": {
        "person": "Tomasz Walkowiak",
        "email": "tomasz.walkowiak@pwr.edu.pl"
    },
    "keywords": ["punctuation"],
    "location": "Wroclaw, Poland",
    "authentication": "Yes, user should create an account on the Clarin-PL website",
    "inputs": [{
        "id": "text",
        "mediatypes": ["application/zip"],
        "languages": ["eng", "pol", "rus"]
    }],
    "webApplication": {
        "url": "https://services.clarin-pl.eu/services/punctuator-premium/creator",
        "queryParameters": [{
            "name": "weblicht-input",
            "bind": "text/dataurl"
        }]
    }
}

=== clarin-eric/switchboard-tool-registry/tools/spaCy monolingual NEL.json
{
	"formatVersion": "2",
    "id": 122123,
    "task": "Named Entity Recognition",
    "deployment": "production",
    "integrationType" : "Integrated",
    "name": "spaCy monolingual NEL",
    "logo": "It-Sr-NER-logo-small.png",
    "homepage": "https://github.com/rankastankovic/It-Sr-NER",
    "location": "Belgrade, Serbia",
    "creators": "Universit√† degli studi di Torino",
    "contact": {
        "person": "Olja Perisic",
        "email": "olja.perisic@unito.it"
    },
    "authentication": "no",
    "description": "NEL web service for monolingual (txt) files.",
    
    "webApplication" : {
		"url": "https://ners.jerteh.rs/api",
    	"queryParameters": [{
			"name": "lng",
			"bind": "file/language",
			"encoding": "639-1"
        }, { 
          		"name": "feat",
			"value": "nel"
       	}, {
          		"name": "data",
			"bind": "file/dataurl",
			"encoding": "639-1"
        }]
          
       
    },
    

     "inputs" : [{
        "id": "file",
        "mediatypes": ["text/plain", "application/xml"],
        "languages": ["generic"]
     }]
      
}
