=== clarin-eric/switchboard-tool-registry/schemas/spec-v2.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://switchboard.clarin.eu/tool-spec-v2.json",
    "title": "JSON Schema for the Switchboard tool specification v.2",
    "type": "object",
    "items": null,
    "required": [
        "formatVersion",
        "id",
        "task",
        "deployment",
        "integrationType",
        "name",
        "description",
        "logo",
        "homepage",
        "creators",
        "contact",
        "inputs"
    ],
    "additionalProperties": false,
    "properties": {
        "formatVersion": {
            "type": "string",
            "enum": ["2"]
        },
        "id": {
            "type": "integer"
        },
        "task": {
            "type": "string",
            "title": "Task description",
            "enum": [
                "Constituency Parsing",
                "Coreference Resolution",
                "Data Conversion",
                "Dependency Parsing",
                "Distant Reading",
                "Editing",
                "Extraction of Polish terminology",
                "Grapheme to Phoneme Conversion",
                "Handwritten Text Recognition",
                "Hyphenation",
                "Inclusion detection",
                "Keyword Extractor",
                "Lemmatization",
                "Lookup Tools",
                "Machine Translation",
                "Metadata Processing",
                "Morpho-syntactic tagger",
                "Morphological Analysis",
                "N-Gramming",
                "Named Entity Recognition",
                "Named Entity Relation Detection",
                "NLP suite for Dutch",
                "Optical Character Recognition",
                "Part-Of-Speech Tagging",
                "Relation between name entities detection",
                "Sentiment Analysis",
                "Shallow Parsing",
                "Spatial expression detection",
                "Speech Recognition",
                "Speech segmentation",
                "Speech transcription",
                "Spelling correction",
                "Stylometry",
                "Text Analytics",
                "Text Enhancement",
                "Text Normalisation",
                "Text Summarization",
                "TF, IDF, TF-IDF calculation",
                "Tokenisation",
                "Topic Modelling",
                "Transliteration",
                "Visualisation of 3D models",
                "Visualisation of Geographic Data",
                "Word sense disambiguation"
            ]
        },
        "deployment": {
            "type": "string",
            "title": "Deployment type",
            "default": "development",
            "enum": ["production", "development"]
        },
        "integrationType": {
            "type": "string",
            "title": "Integration with Switchboard",
            "description": "Integration level: Integrated (fully integrated), External (some parameters must be supplied by the user) and Local (download and install the application locally)",
            "default": "Integrated",
            "enum": ["Integrated", "External", "Local"]
        },
        "name": {
            "title": "Tool name",
            "type": "string"
        },
        "description": {
            "type": "string",
            "title": "Tool's description"
        },
        "logo": {
            "type": "string",
            "title": "The tool's logo file name",
            "examples": ["mylogo.jpg"]
        },
        "homepage": {
            "type": "string",
            "format": "uri",
            "title": "Homepage",
            "examples": ["https://example.com"]
        },
        "keywords": {
            "type": "array",
            "title": "Keywords",
            "items": {"type": "string"}
        },
        "creators": {
            "type": "string",
            "title": "Tool's creators"
        },
        "contact": {
            "type": "object",
            "title": "The Contact Schema",
            "properties": {
                "person": {
                    "type": "string",
                    "title": "Person name"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "title": "Email"
                },
                "url": {
                    "type": "string",
                    "format": "uri",
                    "title": "Contact Page Link"
                }
            },
            "additionalProperties": false
        },
        "location": {
             "type": "string",
            "title": "Geographical location",
            "examples": ["Tuebingen, Germany"]
        },
        "authentication": {
            "type": ["string", "null"],
            "title": "Authentication mechanism description, or null",
            "default": null
        },
        "inputs": {
            "type": "array",
            "title": "Input specs",
            "items": {"$ref": "#/definitions/input_entry"}
        },
        "batchProcessing": {
            "type": "object",
            "title": "Batch processing",
            "properties": {
                "mode": {"type": "string", "enum": ["zip"]},
                "queryParameters": {
                    "type": "array",
                    "title": "Batch mode query parameters",
                    "items": {"$ref": "#/definitions/service_param"}
                }
            }
        },
        "webApplication": {},
        "standaloneApplication": {},
        "usageRestrictions": {
            "type": "object",
            "title": "Usage Restrictions",
            "properties": {
                "individualUserRestrictions": {
                    "type": "string",
                    "enum": ["academic", "public", "regional", "other", "unknown", "license only"]
                },
                "countriesNotSupported": {"type": "string"},
                "countriesSupported": {"type": "string"}
            },
            "additionalProperties": false
        }
    },
    "allOf": [
        {
            "if": {"properties": {"integrationType": {"const": "Local"}}},
            "then": {"properties": {"standaloneApplication": {"$ref": "#/definitions/standalone_application"}}}
        },
        {
            "if": {"properties": {"integrationType": {"const": "Integrated"}}},
            "then": {"properties": {"webApplication": {"$ref": "#/definitions/web_application"}}}
        },
        {
            "if": {"properties": {"integrationType": {"const": "External"}}},
            "then": {"properties": {"webApplication": {
                "allOf": [
                    {"$ref": "#/definitions/web_application"},
                    {"$ref": "#/definitions/with_manual_args"}
                ]}}}
        }
    ],
    "definitions": {
        "web_application": {
            "$id": "#web_application",
            "type": "object",
            "title": "Web Application",
            "properties": {
                "browserRequirements": {"type": "string"},
                "applicationSuite": {"type": "string"},
                "scalabilityType": {
                    "type": "string",
                    "enum": ["singleUser", "smallGroups", "classroomSize", "lectureSize", "unlimited", "unknown", "other"]
                },
                "licenseInformation": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "runtimeInformation": {"$ref": "#/definitions/runtime_information"},
                "url": {
                    "type": "string",
                    "format": "uri",
                    "title": "Tool's URL",
                    "examples": ["https://weblicht.sfs.uni-tuebingen.de/weblicht/"]
                },
                "queryParameters": {
                    "type": "array",
                    "title": "Query parameter list",
                    "items": {"$ref": "#/definitions/service_param"}
                },
                "pathParameters": {
                    "type": "array",
                    "title": "Path parameter list",
                    "items": {"$ref": "#/definitions/service_param"}
                }
            }
        },
        "with_manual_args": {
            "$id": "#with_manual_args",
            "type": "object",
            "title": "Application with manual arguments",
            "properties": {
                "manualParameters": {
                    "type": "array",
                    "title": "Manual parameter list",
                    "items": {"$ref": "#/definitions/service_param"}
                }
            }
        },
        "standalone_application": {
            "$id": "#standalone_application",
            "type": "object",
            "title": "Standalone Application",
            "properties": {
                "availableOnDevice": {
                    "type":"array",
                    "items": {"type": "string"}
                },
                "installURL" : {
                    "type":"array",
                    "items": {"type": "string"}
                },
                "downloadURL" : {
                    "type":"array",
                    "items": {
                        "type": "object",
                        "required": ["type", "url"],
                        "properties": {
                            "type": {"type": "string"},
                            "targetlang": {"$ref": "#/definitions/language_code"},
                            "url": {"type": "string", "format": "uri"},
                            "additionalProperties": false
                        }
                    }
                },
                "applicationSuite": {"type": "string"},
                "featureList": {"type": "string"},
                "permissions": {"type": "string"},
                "releaseNotes": {"type": "string"},
                "softwareAddOn": {"type": "string"},
                "softwareRequirements": {"type": "string"},
                "supportingData": {"type": "string"},
                "dataTransfer": {
                    "type": "string",
                    "enum": ["none", "local", "cloud", "unknown", "other", "N/A"]
                },
                "licenseInformation": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "runtimeInformation": {"$ref": "#/definitions/runtime_information"}
            },
            "additionalProperties": false
        },
        "runtime_information": {
            "$id": "#runtime_information",
            "type": "object",
            "title": "Runtime Information",
            "properties": {
                "memoryRequirements": {"type": "string"},
                "storageRequirements": {"type": "string"},
                "processorRequirements": {"type": "string"},
                "operatingSystem": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {"type": "string"},
                            "versionFrom": {"type": "string"},
                            "versionTo": {"type": "string"}
                        },
                        "additionalProperties": false
                    }
                },
                "fileSize": {"type": "string"},
                "installationLicense": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "runtimeEnvironment": {
                    "type": "array",
                    "items": {"type": "string"}
                }
            },
            "additionalProperties": false
        },
        "service_param": {
            "$id": "#service_param",
            "type": "object",
            "title": "Parameter",
            "properties": {
                "name": {"type": "string"},
                "bind": {"type": "string"},
                "value": {"type": "string"},
                "encoding": {"type": "string"}
            },
            "required": ["name"],
            "additionalProperties": false
        },
        "mimetype_list": {
            "$id": "#mimetype_list",
            "type": "array",
            "title": "Mediatype list",
            "minItems": 1,
            "items": {
                "type": "string",
                "title": "Mediatype",
                "examples": [
                    "text/plain",
                    "text/rtf",
                    "application/pdf",
                    "application/msword"
                ]
            }
        },
        "input_entry": {
            "$id": "#input_entry",
            "type": "object",
            "title": "Input entry",
            "properties": {
                "id": {"type": "string"},
                "name": {"type": "string"},
                "mediatypes": {"$ref": "#/definitions/mimetype_list"},
                "languages": {"oneOf": [
                    {"type": "string"},
                    {"type":"array", "items": {"$ref": "#/definitions/language_code_3"}}
                ]},
                "maxSize": {"type": "integer"},
                "multiple": {"type": "boolean"},
                "optional": {"type": "boolean"}
            },
            "additionalProperties": false
        },
        "language_code_3": {
            "type": "string",
            "title": "Language Identifier, ISO 693-3",
            "default": "eng",
            "examples": ["eng", "deu"],
            "pattern": "^(.{3})$"
        },
        "language_code": {
            "type": "string",
            "title": "Language Identifier, ISO 693-3",
            "default": "eng",
            "examples": ["eng", "deu"],
            "pattern": "^(.{2,3})$"
        }
    }
}

=== clarin-eric/switchboard-tool-registry/tools/spaCy bilingual NER.json
{
	"formatVersion": "2",
    "id": 122126,
    "task": "Named Entity Recognition",
    "deployment": "production",
    "integrationType" : "Integrated",
    "name": "spaCy bilingual NER (for TMX)",
    "logo": "It-Sr-NER-logo-small.png",
    "homepage": "https://github.com/rankastankovic/It-Sr-NER",
    "location": "Belgrade, Serbia",
    "creators": "Universit√† degli studi di Torino",
    "contact": {
        "person": "Olja Perisic",
        "email": "olja.perisic@unito.it"
    },
    "authentication": "no",
    "description": "NER web service for parallel text (tmx) files.",
    
    "webApplication" : {
		"url": "https://ners.jerteh.rs/api",
    	"queryParameters": [ { 
          		"name": "feat",
			"value": "ner"
       	}, {
          		"name": "data",
			"bind": "file/dataurl",
			"encoding": "639-1"
        }]
          
       
    },
    
     "inputs" : [{
        "id": "file",
        "mediatypes": ["application/xml"]}]
      
}

=== clarin-eric/switchboard-tool-registry/tools/topicsexplorer.json
{
    "id": 150,
    "formatVersion": "2",
    "task": "Topic Modelling",
    "deployment": "production",
    "integrationType": "Local",
    "name": "TopicsExplorer",
    "logo": "dariah-de.svg",
    "homepage": "https://dariah-de.github.io/TopicsExplorer/",
    "description": "The Topicsexplorer is a beginner-oriented Software allowing interested researchers to experiment with topic modeling on their own computers, with their own text corpora.",
    "location": "",
    "creators": "",
    "contact": {
        "email": "info@de.dariah.eu"
    },
    "inputs": [
        {
            "id": "input",
            "mediatypes": [
                "text/plain",
                "text/xml"
            ],
            "languages": "generic"
        }
    ],
    "standaloneApplication": {
        "downloadURL": [
            {
                "url": "https://github.com/DARIAH-DE/TopicsExplorer/releases/tag/v2.0",
                "type": "release"
            },
            {
                "url": "https://github.com/DARIAH-DE/TopicsExplorer/releases/tag/v2.0",
                "type": "preview"
            }
        ],
        "applicationSuite": "TopicsExplorer",
        "licenseInformation": [
            "Apache License, Version 2.0"
        ]
    },
    "authentication": null,
    "keywords": [
        "Topic modeling"
    ],
    "usageRestrictions": {
        "individualUserRestrictions": "academic"
    }
}

=== clarin-eric/switchboard-tool-registry/tools/Paraphrase.json
{
    "formatVersion": "2",
    "id": 90,
    "task": "Editing",
    "deployment": "production",
    "integrationType": "Integrated",
    "name": "TxTParaphrase",
    "description": "Based on a deep language model that analyzes the semantic content of statements and generates texts with the same meaning but with a changed form. The tool returns text of a similar length to the text entered by the user.",
    "logo": "clarin-pl.png",
    "homepage": "https://services.clarin-pl.eu/services/paraphrase",
    "creators": "Clarin-PL",
    "contact": {
        "person": "Tomasz Walkowiak",
        "email": "tomasz.walkowiak@pwr.edu.pl"
    },
    "keywords": ["paraphrase", "text", "semantic content"],
    "location": "Wroclaw, Poland",
    "authentication": "Yes, user should create an account on the Clarin-PL website",
    "inputs": [{
        "id": "text",
        "mediatypes": ["application/zip"],
        "languages": ["eng", "pol"]
    }],
    "webApplication": {
        "url": "https://services.clarin-pl.eu/services/paraphrase/creator",
        "queryParameters": [{
            "name": "weblicht-input",
            "bind": "text/dataurl"
        }]
    }
}

=== clarin-eric/switchboard-tool-registry/tools/LiLa_Textlinker.json
{
    "formatVersion": "2",
    "id": 250,
    "task": "Lemmatization",
    "deployment": "production",
    "integrationType": "Integrated",
    "name": "LiLa Text Linker",
    "description": "......",
    "logo": "LiLaLogo.png",
    "homepage": "https://lila-erc.eu",
    "creators": "CIRCSE Research center - Universit√† Cattolica del Sacro Cuore",
    "contact": {
        "person": "Marco Passarotti",
        "email": "info@lila-erc.eu"
    },
    "keywords": ["lemmatization", "lemmatisation", "POS", "LOD", "LiLa", "Linked open data", "NLP", "latin"],
    "location": "Milan - Italy",
    "authentication": "no",
    "inputs": [{
        "id": "text",
        "mediatypes": [
            "text/plain"
        ],
        "languages": ["lat"],
        "maxSize": 8000,
        "multiple": false
    }],
    "webApplication": {
        "url": "https://lila-erc.eu/LiLaTextLinker/process",
        "queryParameters": [{
            "name": "text",
            "bind": "text/plain"
        }]
    }
}

=== clarin-eric/switchboard-tool-registry/tools/Dewulgaryzator.json
{
    "formatVersion": "2",
    "id": 191,
    "task": "Editing",
    "deployment": "production",
    "integrationType": "Integrated",
    "name": "Dewulgaryzator",
    "description": "Service that allows you to replace vulgar expressions with their non-vulgar equivalents while maintaining the original character of the text.",
    "logo": "clarin-pl.png",
    "homepage": "https://services.clarin-pl.eu/services/txt2txt",
    "creators": "Clarin-PL",
    "contact": {
        "person": "Tomasz Walkowiak",
        "email": "tomasz.walkowiak@pwr.edu.pl"
    },
    "keywords": ["profanity", "substitution", "vulgar"],
    "location": "Wroclaw, Poland",
    "authentication": "Yes, user should create an account on the Clarin-PL website",
    "inputs": [{
        "id": "text",
        "mediatypes": ["application/zip"],
        "languages": ["pol"]
    }],
    "webApplication": {
        "url": "https://services.clarin-pl.eu/services/txt2txt/creator",
        "queryParameters": [{
            "name": "weblicht-input",
            "bind": "text/dataurl"
        }]
    }
}

=== clarin-eric/switchboard-tool-registry/tools/Anonymizer.json
{
    "formatVersion": "2",
    "id": 51,
    "task": "Editing",
    "deployment": "production",
    "integrationType": "Integrated",
    "name": "Anonymizer",
    "description": "Anonymized data is not subject to GDPR and does not pose any other threats to privacy - so it can be archived without risk and freely transferred between departments or to external companies without the use of trustee agreements.",
    "logo": "clarin-pl.png",
    "homepage": "https://services.clarin-pl.eu/services/anonymizer",
    "creators": "Clarin-PL",
    "contact": {
        "person": "Tomasz Walkowiak",
        "email": "tomasz.walkowiak@pwr.edu.pl"
    },
    "keywords": ["anonymization", "gdpr", "rodo", "privacy", "data protection", "personal data", "data security"],
    "location": "Wroclaw, Poland",
    "authentication": "Yes, user should create an account on the Clarin-PL website",
    "inputs": [{
        "id": "text",
        "mediatypes": ["application/zip"],
        "languages": ["eng", "pol"]
    }],
    "webApplication": {
        "url": "https://services.clarin-pl.eu/services/anonymizer/creator",
        "queryParameters": [{
            "name": "weblicht-input",
            "bind": "text/dataurl"
        }]
    }
}

=== clarin-eric/switchboard-tool-registry/tools/spaCy monolingual and bilingual NER and NEL.json
{
	"formatVersion": "2",
    "id": 122121,
    "task": "Named Entity Recognition",
    "deployment": "production",
    "integrationType" : "Integrated",
    "name": "spaCy monolingual and bilingual NER and NEL",
    "logo": "It-Sr-NER-logo-small.png",
    "homepage": "https://github.com/rankastankovic/It-Sr-NER",
    "location": "Belgrade, Serbia",
    "creators": "Universit√† degli studi di Torino",
    "contact": {
        "person": "Olja Perisic",
        "email": "olja.perisic@unito.it"
    },
    "authentication": "no",
    "description": "NER and NEL web service for monolingual (txt) and parallel text (tmx).",
    
    "webApplication" : {
		"url": "https://ners.jerteh.rs/api",
    	"queryParameters": [{
			"name": "lng",
			"bind": "file/language",
			"encoding": "639-1"
        }, { 
          		"name": "feat",
			"value": "nernel"
       	}, {
          		"name": "data",
			"bind": "file/dataurl",
			"encoding": "639-1"
        }]
          
       
    },
    

     "inputs" : [{
        "id": "file",
        "mediatypes": ["text/plain", "application/xml"],
        "languages": ["generic", "cat", "zho", "hrv", "dan",  "nld", "eng", "fin", "fra", "deu", "ell", "ita", "jpn", "kor", "lit", "mkd", "nob", "pol", "por", "ron", "rus", "spa", "swe", "ukr", "srp"]
     }]
      
}

=== clarin-eric/switchboard-tool-registry/tools/Geolocation.json
{
    "formatVersion": "2",
    "id": 111,
    "task": "Visualisation of Geographic Data",
    "deployment": "production",
    "integrationType": "Integrated",
    "name": "Dewulgaryzator",
    "description": "Tool based on the Named Entity Recognition service, assigning geographic coordinates to detected place names.",
    "logo": "clarin-pl.png",
    "homepage": "https://services.clarin-pl.eu/services/geolocation",
    "creators": "Clarin-PL",
    "contact": {
        "person": "Tomasz Walkowiak",
        "email": "tomasz.walkowiak@pwr.edu.pl"
    },
    "keywords": ["geolocation", "named entity recognition", "place names", "geographic coordinates"],
    "location": "Wroclaw, Poland",
    "authentication": "Yes, user should create an account on the Clarin-PL website",
    "inputs": [{
        "id": "text",
        "mediatypes": ["application/zip"],
        "languages": ["pol", "eng"]
    }],
    "webApplication": {
        "url": "https://services.clarin-pl.eu/services/geolocation/creator",
        "queryParameters": [{
            "name": "weblicht-input",
            "bind": "text/dataurl"
        }]
    }
}
