=== clarin-eric/switchboard-tool-registry/schemas/spec-v1.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://switchboard.clarin.eu/tool-spec-v1.json",
  "title": "JSON Schema for the Switchboard tool specification",
  "type": "object",
  "items": null,
  "definitions": {},
  "required": [
    "task",
    "deployment",
    "name",
    "description",
    "logo",
    "homepage",
    "location",
    "creators",
    "contact",
    "version",
    "authentication",
    "licence",
    "output",
    "mimetypes",
    "languages",
    "langEncoding",
    "parameters",
    "url"
  ],
  "properties": {
    "task": {
      "$id": "#/properties/task",
      "type": "string",
      "title": "Task description",
      "enum": [
        "3D Visualisation",
        "Constituency Parsing",
        "Coreference Resolution",
        "Data Conversion",
        "Dependency Parsing",
        "Distant Reading",
        "Dictionary",
        "Extraction of Polish terminology",
        "Grapheme to Phoneme Conversion",
        "Handwritten Text Recognition",
        "Inclusion detection",
        "Keyword Extractor",
        "Lemmatization",
        "Machine Translation",
        "Metadata Processing",
        "Morpho-syntactic tagger",
        "Morphological Analysis",
        "N-Gramming",
        "Named Entity Recognition",
        "NLP suite for Dutch",
        "Optical Character Recognition",
        "Part-Of-Speech Tagging",
        "Relation between name entities detection",
        "Sentiment Analysis",
        "Shallow Parsing",
        "Spatial expression detection",
        "Speech Recognition",
        "Spelling correction",
        "Stylometry",
        "Text Analytics",
        "Text Enhancement",
        "Text Normalisation",
        "Text Summarization",
        "TF, IDF, TF-IDF calculation",
        "Tokenisation",
        "Topic Modelling",
        "Transliteration",
        "Visualisation",
        "Word sense disambiguation"
      ]
    },
    "deployment": {
      "$id": "#/properties/deployment",
      "type": "string",
      "title": "Deployment type",
      "default": "development",
      "enum": ["production", "development"]
    },
    "name": {
      "$id": "#/properties/name",
      "title": "Tool name",
      "type": "string"
    },
    "logo": {
      "$id": "#/properties/logo",
      "type": "string",
      "title": "The tool's logo file name",
      "examples": ["mylogo.jpg"]
    },
    "homepage": {
      "$id": "#/properties/homepage",
      "type": "string",
      "format": "uri",
      "title": "Homepage",
      "examples": ["https://example.com"]
    },
    "location": {
      "$id": "#/properties/location",
      "type": "string",
      "title": "Geographical location",
      "examples": ["Tuebingen, Germany"]
    },
    "creators": {
      "$id": "#/properties/creators",
      "type": "string",
      "title": "Tool's creators"
    },
    "contact": {
      "$id": "#/properties/contact",
      "type": "object",
      "title": "The Contact Schema",
      "required": [
        "person",
        "email"
      ],
      "properties": {
        "person": {
          "$id": "#/properties/contact/properties/person",
          "type": "string",
          "title": "Person name"
        },
        "email": {
          "$id": "#/properties/contact/properties/email",
          "type": "string",
          "format": "email",
          "title": "Email"
        }
      }
    },
    "version": {
      "$id": "#/properties/version",
      "type": ["string", "null"],
      "title": "Tool's version",
      "default": null,
      "examples": ["v1.0"]
    },
    "authentication": {
      "$id": "#/properties/authentication",
      "type": ["string", "null"],
      "title": "Authentication mechanism description, or null",
      "default": null
    },
    "licence": {
      "$id": "#/properties/licence",
      "type": ["string", "null"],
      "title": "Tool's licence",
      "default": null
    },
    "description": {
      "$id": "#/properties/description",
      "type": "string",
      "title": "Tool's description"
    },
    "languages": {
      "$id": "#/properties/languages",
      "type": "array",
      "title": "Languages that the tool can work with",
      "items": {
        "$id": "#/properties/languages/items",
        "type": "string",
        "title": "Language Identifier, ISO 693-3",
        "default": "eng",
        "examples": ["eng", "deu"],
        "pattern": "^(.{3})|(generic)$"
      }
    },
    "langEncoding": {
      "$id": "#/properties/langEncoding",
      "type": "string",
      "title": "The language encoding that the tool requires",
      "default": "639-3",
      "enum": ["639-1", "639-3"]
    },
    "mimetypes": {
      "$id": "#/properties/mimetypes",
      "type": "array",
      "title": "Accepted mimetypes",
      "items": {
        "$id": "#/properties/mimetypes/items",
        "type": "string",
        "title": "Mediatype",
        "examples": [
          "text/plain",
          "text/rtf",
          "application/pdf",
          "application/msword"
        ]
      }
    },
    "output": {
      "$id": "#/properties/output",
      "type": "array",
      "title": "Tool's output mediatypes",
      "items": {
        "$id": "#/properties/output/items",
        "type": "string",
        "title": "Mediatype",
        "examples": ["application/xml"]
      }
    },
    "url": {
      "$id": "#/properties/url",
      "type": "string",
      "format": "uri",
      "title": "Tool's URL",
      "examples": ["https://weblicht.sfs.uni-tuebingen.de/weblicht/"]
    },
    "parameters": {
      "$id": "#/properties/parameters",
      "type": "object",
      "title": "Tool parameters"
    }
  }
}

=== clarin-eric/switchboard-tool-registry/tools/DARIAH-DE-Geo-Browser.json
{
    "task": "Visualisation",
    "deployment": "development",
    "name": "DARIAH-DE Geo-Browser",
    "logo": "dariah.svg",
    "homepage": "https://de.dariah.eu/en/geobrowser",
    "location": "Göttingen, Germany",
    "creators": "Ubbo Veentjer (SUB Göttingen) and Stefan E. Funk (SUB Göttingen)",
    "contact": {
        "person": "Stefan E Funk",
        "email": "support@de.dariah.eu"
    },
    "version": "v3.6-BETA",
    "authentication": "DARIAH AAI (restricted resources), none (public resources)",
    "description": "The DARIAH-DE Geo-Browser allows a comparative visualization of several requests and facilitates the representation of data and their visualization in a correlation of geographic spatial relations at corresponding points of time and sequences. Thus, researchers can analyze space-time relations of data and collections of source material and simultaneously establish correlations between them. This sample dataset for the Geo-Browser shows publishing dates and locations of works by Friedrich Schiller and Johann Wolfgang von Goethe plotted against each other.",
    "licence": "LGPL-3.0-or-later",
    "output": [
        "none"
    ],
    "mimetypes": [
        "text/csv",
        "application/vnd.google-earth.kml+xml",
        "application/vnd.google-earth.kmz",
        "application/vnd.dariahde.geobrowser.kml+xml",
        "application/vnd.dariahde.geobrowser.csv"
    ],
    "languages": [
        "eng",
        "generic"
    ],
    "langEncoding": "639-1",
    "parameters": {
        "input": "self.linkToResource"
    },
    "url": "https://geobrowser.de.dariah.eu/beta/"
}

=== clarin-eric/switchboard-tool-registry/tools/Tagger NLTK.json
{
    "task": "Morpho-syntactic tagger",
    "deployment": "production",
    "name": "Tagger NLTK",
    "logo": "clarin-pl.png",
    "homepage": "https://ws.clarin-pl.eu",
    "location": "Wroc≈Çaw, Poland",
    "creators": "Clarin-PL",
    "contact": {
        "person": "Tomasz Walkowiak",
        "email": "tomasz.walkowiak@pwr.edu.pl"
    },
    "version": "1.0",
    "licence": null,
    "authentication": "no",
    "description": "Morpho-syntactic tagger for English texts.",
    "languages": [
        "eng"
    ],
    "langEncoding": "639-1",
    "mimetypes": [
        "text/plain",
        "application/msword",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/vnd.oasis.opendocument.text",
        "application/pdf",
        "text/rtf"
    ],
    "output": [
        "application/xml"
    ],
    "url": "https://ws.clarin-pl.eu/weblicht.html",
    "parameters": {
        "input": null,
        "lang": "en",
        "analysis": "tagerNLTK"
    }
}

=== clarin-eric/switchboard-tool-registry/tools/WoSeDon.json
{
    "task": "Word sense disambiguation",
    "deployment": "production",
    "name": "WoSeDon",
    "logo": "clarin-pl.png",
    "homepage": "https://ws.clarin-pl.eu",
    "location": "Wroc≈Çaw, Poland",
    "creators": "Clarin-PL",
    "contact": {
        "person": "Tomasz Walkowiak",
        "email": "tomasz.walkowiak@pwr.edu.pl"
    },
    "version": "1.0",
    "licence": null,
    "authentication": "no",
    "description": "Word Sense Disambiguation for Polish texts based on plWordNet - the Polish wordnet (weakly supervised, for all words).",
    "languages": [
        "pol"
    ],
    "langEncoding": "639-1",
    "mimetypes": [
        "text/plain",
        "application/msword",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/vnd.oasis.opendocument.text",
        "application/pdf",
        "text/html",
        "text/rtf"
    ],
    "output": [
        "application/xml"
    ],
    "url": "https://ws.clarin-pl.eu/weblicht.html",
    "parameters": {
        "input": null,
        "lang": "pl",
        "analysis": "wsd"
    }
}

=== clarin-eric/switchboard-tool-registry/tools/WebLicht-Dep-Parsing-HR (RELDI).json
{
    "task": "Dependency Parsing",
    "deployment": "development",
    "name": "WebLicht Dep Parsing HR (RELDI)",
    "logo": "weblicht.jpg",
    "homepage": "https://weblicht.sfs.uni-tuebingen.de/weblichtwiki/index.php/Main_Page",
    "location": "Tuebingen, Germany",
    "creators": "CLARIN-D Centre at the University of Tuebingen, Germany",
    "contact": {
        "person": "CLARIN WebLicht Support",
        "email": "wlsupport@sfs.uni-tuebingen.de"
    },
    "version": "v1.0",
    "authentication": "Requires a CLARIN Service Provider Federation account, provided by many universities and institutions.",
    "licence": null,
    "description": "WebLicht Easy Chain for Dependency Parsing (Croatian). The easy-chain makes use of the RELDI software (see https://github.com/clarinsi), which tokenizes and lemmatizes the text, performs part-of-speech tagging, and subsequently, does dependency parsing. For RELDI specific inquiries, please contact nljubesi@gmail.com.",
    "languages": [
        "hrv"
    ],
    "langEncoding": "639-1",
    "mimetypes": [
        "text/plain",
        "text/rtf",
        "application/pdf",
        "application/msword",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    ],
    "output": [
        "application/tcf+xml"
    ],
    "url": "https://weblicht.sfs.uni-tuebingen.de/weblicht/",
    "parameters": {
        "input": null,
        "lang": "hr",
        "analysis": "dep-parsing"
    }
}

=== clarin-eric/switchboard-tool-registry/tools/WebLicht.json
{
    "task": "Text Analytics",
    "deployment": "production",
    "name": "WebLicht Advanced Mode",
    "logo": "weblicht.jpg",
    "homepage": "https://weblicht.sfs.uni-tuebingen.de/weblichtwiki/index.php/Main_Page",
    "location": "Tuebingen, Germany",
    "creators": "CLARIN-D Centre at the University of Tuebingen, Germany",
    "contact": {
        "person": "CLARIN WebLicht Support",
        "email": "wlsupport@sfs.uni-tuebingen.de"
    },
    "version": "v1.0",
    "authentication": "Requires a CLARIN Service Provider Federation account, provided by many universities and institutions.",
    "licence": null,
    "description": "This tool links to the WebLicht environment without preselecting an execution chain. WebLicht is an execution environment for automatic annotation of text corpora. Linguistic tools such as tokenizers, part of speech taggers, and parsers are encapsulated as web services, which can be combined by the user into custom processing chains. The resulting annotations can then be visualized in an appropriate way, such as in a table or tree format.",
    "languages": ["generic"],
    "langEncoding": "639-1",
    "mimetypes": [
        "text/plain",
        "text/rtf",
        "application/pdf",
        "application/msword",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    ],
    "output": [
        "application/tcf+xml"
    ],
    "url": "https://weblicht.sfs.uni-tuebingen.de/weblicht/",
    "parameters": {
        "input": "",
        "lang": ""
    }
}

=== clarin-eric/switchboard-tool-registry/tools/Concraft.json
{
    "task": "Part-Of-Speech Tagging",
    "deployment": "production",
    "name": "Concraft",
    "logo": "zil.png",
    "homepage": "http://zil.ipipan.waw.pl/Concraft",
    "location": "Warsaw, Poland",
    "creators": "Institute of Computer Science, Polish Academy of Sciences, Poland",
    "contact": {
        "person": "MultiService",
        "email": "rjawor@amu.edu.pl"
    },
    "version": "v1.0",
    "authentication": "no",
    "licence": null,
    "description": "Morphosyntactic tagger for Polish based on constrained conditional random fields. Part of: Multiservice, a robust  linguistic Web service for Polish.",
    "languages": [
        "pol"
    ],
    "langEncoding": "639-1",
    "mimetypes": [
        "text/plain",
        "text/html"
    ],
    "output": [
        "application/json",
        "CoNLL format",
        "Visualization"
    ],
    "url": "http://multiservice.nlp.ipipan.waw.pl/en/clrs",
    "parameters": {
        "input": null,
        "analysis": "0"
    }
}
