=== clarin-eric/switchboard-tool-registry/schemas/spec-v2.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://switchboard.clarin.eu/tool-spec-v2.json",
    "title": "JSON Schema for the Switchboard tool specification v.2",
    "type": "object",
    "items": null,
    "required": [
        "formatVersion",
        "id",
        "task",
        "deployment",
        "integrationType",
        "name",
        "description",
        "logo",
        "homepage",
        "creators",
        "contact",
        "inputs"
    ],
    "additionalProperties": false,
    "properties": {
        "formatVersion": {
            "type": "string",
            "enum": ["2"]
        },
        "id": {
            "type": "integer"
        },
        "task": {
            "type": "string",
            "title": "Task description",
            "enum": [
                "Constituency Parsing",
                "Coreference Resolution",
                "Data Conversion",
                "Dependency Parsing",
                "Distant Reading",
                "Editing",
                "Extraction of Polish terminology",
                "Grapheme to Phoneme Conversion",
                "Handwritten Text Recognition",
                "Hyphenation",
                "Inclusion detection",
                "Keyword Extractor",
                "Lemmatization",
                "Lookup Tools",
                "Machine Translation",
                "Metadata Processing",
                "Morpho-syntactic tagger",
                "Morphological Analysis",
                "N-Gramming",
                "Named Entity Recognition",
                "Named Entity Relation Detection",
                "NLP suite for Dutch",
                "Optical Character Recognition",
                "Part-Of-Speech Tagging",
                "Relation between name entities detection",
                "Sentiment Analysis",
                "Shallow Parsing",
                "Spatial expression detection",
                "Speech Recognition",
                "Speech segmentation",
                "Speech transcription",
                "Spelling correction",
                "Stylometry",
                "Text Analytics",
                "Text Enhancement",
                "Text Normalisation",
                "Text Summarization",
                "TF, IDF, TF-IDF calculation",
                "Tokenisation",
                "Topic Modelling",
                "Transliteration",
                "Visualisation of 3D models",
                "Visualisation of Geographic Data",
                "Word sense disambiguation"
            ]
        },
        "deployment": {
            "type": "string",
            "title": "Deployment type",
            "default": "development",
            "enum": ["production", "development"]
        },
        "integrationType": {
            "type": "string",
            "title": "Integration with Switchboard",
            "description": "Integration level: Integrated (fully integrated), External (some parameters must be supplied by the user) and Local (download and install the application locally)",
            "default": "Integrated",
            "enum": ["Integrated", "External", "Local"]
        },
        "name": {
            "title": "Tool name",
            "type": "string"
        },
        "description": {
            "type": "string",
            "title": "Tool's description"
        },
        "logo": {
            "type": "string",
            "title": "The tool's logo file name",
            "examples": ["mylogo.jpg"]
        },
        "homepage": {
            "type": "string",
            "format": "uri",
            "title": "Homepage",
            "examples": ["https://example.com"]
        },
        "keywords": {
            "type": "array",
            "title": "Keywords",
            "items": {"type": "string"}
        },
        "creators": {
            "type": "string",
            "title": "Tool's creators"
        },
        "contact": {
            "type": "object",
            "title": "The Contact Schema",
            "properties": {
                "person": {
                    "type": "string",
                    "title": "Person name"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "title": "Email"
                },
                "url": {
                    "type": "string",
                    "format": "uri",
                    "title": "Contact Page Link"
                }
            },
            "additionalProperties": false
        },
        "location": {
             "type": "string",
            "title": "Geographical location",
            "examples": ["Tuebingen, Germany"]
        },
        "authentication": {
            "type": ["string", "null"],
            "title": "Authentication mechanism description, or null",
            "default": null
        },
        "inputs": {
            "type": "array",
            "title": "Input specs",
            "items": {"$ref": "#/definitions/input_entry"}
        },
        "batchProcessing": {
            "type": "object",
            "title": "Batch processing",
            "properties": {
                "mode": {"type": "string", "enum": ["zip"]},
                "queryParameters": {
                    "type": "array",
                    "title": "Batch mode query parameters",
                    "items": {"$ref": "#/definitions/service_param"}
                }
            }
        },
        "webApplication": {},
        "standaloneApplication": {},
        "usageRestrictions": {
            "type": "object",
            "title": "Usage Restrictions",
            "properties": {
                "individualUserRestrictions": {
                    "type": "string",
                    "enum": ["academic", "public", "regional", "other", "unknown", "license only"]
                },
                "countriesNotSupported": {"type": "string"},
                "countriesSupported": {"type": "string"}
            },
            "additionalProperties": false
        }
    },
    "allOf": [
        {
            "if": {"properties": {"integrationType": {"const": "Local"}}},
            "then": {"properties": {"standaloneApplication": {"$ref": "#/definitions/standalone_application"}}}
        },
        {
            "if": {"properties": {"integrationType": {"const": "Integrated"}}},
            "then": {"properties": {"webApplication": {"$ref": "#/definitions/web_application"}}}
        },
        {
            "if": {"properties": {"integrationType": {"const": "External"}}},
            "then": {"properties": {"webApplication": {
                "allOf": [
                    {"$ref": "#/definitions/web_application"},
                    {"$ref": "#/definitions/with_manual_args"}
                ]}}}
        }
    ],
    "definitions": {
        "web_application": {
            "$id": "#web_application",
            "type": "object",
            "title": "Web Application",
            "properties": {
                "browserRequirements": {"type": "string"},
                "applicationSuite": {"type": "string"},
                "scalabilityType": {
                    "type": "string",
                    "enum": ["singleUser", "smallGroups", "classroomSize", "lectureSize", "unlimited", "unknown", "other"]
                },
                "licenseInformation": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "runtimeInformation": {"$ref": "#/definitions/runtime_information"},
                "url": {
                    "type": "string",
                    "format": "uri",
                    "title": "Tool's URL",
                    "examples": ["https://weblicht.sfs.uni-tuebingen.de/weblicht/"]
                },
                "queryParameters": {
                    "type": "array",
                    "title": "Query parameter list",
                    "items": {"$ref": "#/definitions/service_param"}
                },
                "pathParameters": {
                    "type": "array",
                    "title": "Path parameter list",
                    "items": {"$ref": "#/definitions/service_param"}
                }
            }
        },
        "with_manual_args": {
            "$id": "#with_manual_args",
            "type": "object",
            "title": "Application with manual arguments",
            "properties": {
                "manualParameters": {
                    "type": "array",
                    "title": "Manual parameter list",
                    "items": {"$ref": "#/definitions/service_param"}
                }
            }
        },
        "standalone_application": {
            "$id": "#standalone_application",
            "type": "object",
            "title": "Standalone Application",
            "properties": {
                "availableOnDevice": {
                    "type":"array",
                    "items": {"type": "string"}
                },
                "installURL" : {
                    "type":"array",
                    "items": {"type": "string"}
                },
                "downloadURL" : {
                    "type":"array",
                    "items": {
                        "type": "object",
                        "required": ["type", "url"],
                        "properties": {
                            "type": {"type": "string"},
                            "targetlang": {"$ref": "#/definitions/language_code"},
                            "url": {"type": "string", "format": "uri"},
                            "additionalProperties": false
                        }
                    }
                },
                "applicationSuite": {"type": "string"},
                "featureList": {"type": "string"},
                "permissions": {"type": "string"},
                "releaseNotes": {"type": "string"},
                "softwareAddOn": {"type": "string"},
                "softwareRequirements": {"type": "string"},
                "supportingData": {"type": "string"},
                "dataTransfer": {
                    "type": "string",
                    "enum": ["none", "local", "cloud", "unknown", "other", "N/A"]
                },
                "licenseInformation": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "runtimeInformation": {"$ref": "#/definitions/runtime_information"}
            },
            "additionalProperties": false
        },
        "runtime_information": {
            "$id": "#runtime_information",
            "type": "object",
            "title": "Runtime Information",
            "properties": {
                "memoryRequirements": {"type": "string"},
                "storageRequirements": {"type": "string"},
                "processorRequirements": {"type": "string"},
                "operatingSystem": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {"type": "string"},
                            "versionFrom": {"type": "string"},
                            "versionTo": {"type": "string"}
                        },
                        "additionalProperties": false
                    }
                },
                "fileSize": {"type": "string"},
                "installationLicense": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "runtimeEnvironment": {
                    "type": "array",
                    "items": {"type": "string"}
                }
            },
            "additionalProperties": false
        },
        "service_param": {
            "$id": "#service_param",
            "type": "object",
            "title": "Parameter",
            "properties": {
                "name": {"type": "string"},
                "bind": {"type": "string"},
                "value": {"type": "string"},
                "encoding": {"type": "string"}
            },
            "required": ["name"],
            "additionalProperties": false
        },
        "mimetype_list": {
            "$id": "#mimetype_list",
            "type": "array",
            "title": "Mediatype list",
            "minItems": 1,
            "items": {
                "type": "string",
                "title": "Mediatype",
                "examples": [
                    "text/plain",
                    "text/rtf",
                    "application/pdf",
                    "application/msword"
                ]
            }
        },
        "input_entry": {
            "$id": "#input_entry",
            "type": "object",
            "title": "Input entry",
            "properties": {
                "id": {"type": "string"},
                "name": {"type": "string"},
                "mediatypes": {"$ref": "#/definitions/mimetype_list"},
                "languages": {"oneOf": [
                    {"type": "string"},
                    {"type":"array", "items": {"$ref": "#/definitions/language_code_3"}}
                ]},
                "maxSize": {"type": "integer"},
                "multiple": {"type": "boolean"},
                "optional": {"type": "boolean"}
            },
            "additionalProperties": false
        },
        "language_code_3": {
            "type": "string",
            "title": "Language Identifier, ISO 693-3",
            "default": "eng",
            "examples": ["eng", "deu"],
            "pattern": "^(.{3})$"
        },
        "language_code": {
            "type": "string",
            "title": "Language Identifier, ISO 693-3",
            "default": "eng",
            "examples": ["eng", "deu"],
            "pattern": "^(.{2,3})$"
        }
    }
}

=== clarin-eric/switchboard-tool-registry/tools/dkpro_wrapper_Hyphenation_DE.json
{
    "id": 144,
    "formatVersion": "2",
    "task": "Hyphenation",
    "deployment": "production",
    "integrationType": "Local",
    "name": "DARIAH DKPro-Wrapper: Hyphenation DE",
    "logo": "dariah-de.svg",
    "homepage": "http://dariah-de.github.io/DARIAH-DKPro-Wrapper/",
    "description": "The DARIAH DKPro Wrapper is a wrapper for DKPro Core, a tool for linguistic annotation.",
    "location": "",
    "creators": "",
    "contact": {
        "email": "info@de.dariah.eu"
    },
    "inputs": [
        {
            "id": "input",
            "mediatypes": [
                "text/plain",
                "text/xml"
            ],
            "languages": [
                "deu"
            ]
        }
    ],
    "standaloneApplication": {
        "downloadURL": [
            {
                "url": "https://github.com/DARIAH-DE/DARIAH-DKPro-Wrapper/releases",
                "type": "release"
            },
            {
                "url": "https://github.com/DARIAH-DE/DARIAH-DKPro-Wrapper/releases",
                "type": "preview"
            }
        ],
        "applicationSuite": "DARIAH-DE DKPro-Wrapper",
        "featureList": "https://dkpro.github.io/dkpro-core/releases/2.1.0/docs/language-reference.html#_overview",
        "licenseInformation": [
            "Apache License, Version 2.0. Component licenses apply (see https://github.com/DARIAH-DE/DARIAH-DKPro-Wrapper/blob/master/License_Components.txt)"
        ],
        "runtimeInformation": {
            "memoryRequirements": "4GB",
            "runtimeEnvironment": [
                "Java 1.8 or higher, 64bit"
            ]
        }
    },
    "authentication": null,
    "keywords": [
        "Cleanup"
    ],
    "usageRestrictions": {
        "individualUserRestrictions": "academic"
    }
}

=== clarin-eric/switchboard-tool-registry/tools/Lem.json
{
    "formatVersion": "2",
    "id": 92,
    "task": "Text Analytics",
    "deployment": "production",
    "integrationType": "Integrated",
    "name": "LEM",
    "description": "Service that is used to process literary texts to extract statistical information from them. The service allows, among others, lemmatization, determining parts of speech, characterization of verbs used in the text, creating a list of proper names and extracting statistics from the corpus of texts.",
    "logo": "clarin-pl.png",
    "homepage": "https://services.clarin-pl.eu/services/statconverter",
    "creators": "Clarin-PL",
    "contact": {
        "person": "Tomasz Walkowiak",
        "email": "tomasz.walkowiak@pwr.edu.pl"
    },
    "keywords": ["lemmatization", "part of speech", "verbs", "proper names", "statistics"],
    "location": "Wroclaw, Poland",
    "authentication": "Yes, user should create an account on the Clarin-PL website",
    "inputs": [{
        "id": "text",
        "mediatypes": ["application/zip"],
        "languages": ["pol"]
    }],
    "webApplication": {
        "url": "https://services.clarin-pl.eu/services/statconverter/creator",
        "queryParameters": [{
            "name": "weblicht-input",
            "bind": "text/dataurl"
        }]
    }
}

=== clarin-eric/switchboard-tool-registry/tools/texton-advanced.json
{
    "formatVersion": "2",
    "id": 222,
    "task": "Text Analytics",
    "deployment": "production",
    "integrationType": "Integrated",
    "name": "Text Tonsorium - Advanced mode.",
    "description": "The Text Tonsorium designs and enacts workflows that fulfil your goal. Once in Text Tonsorium, you can define your goal by picking values from a few drop-down lists, e.g., annotation types in and file format of the output. Some annotation types are only available for a few languages, first and foremost Danish. In case your goal cannot be attained with the currently available tools, the Text Tonsorium will quickly let you know.",
    "logo": "texton.png",
    "homepage": "https://cst.dk/texton/help",
    "creators": "CLARIN B-centre at the University of Copenhagen, Denmark",
    "contact": {
        "person": "Bart Jongejan",
        "email": "bartj@hum.ku.dk"
    },
    "keywords": [ "lemmatization", "lemmatisation", "Part of Speech", "Dependency parsing", "Tokenisation", "Named entities", "TEI P5", "CONLL", "HTML", "JSON", "PDF", "Word", "contemporary", "late modern", "medieval", "classic", "OCR", "fraktur", "Danish" ],
    "location": "Copenhagen, Denmark",
    "authentication": "no",
    "inputs": [
        {
            "id": "text",
            "mediatypes": [
                "application/pdf",
                "application/vnd.ms-powerpoint",
                "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                "application/vnd.oasis.opendocument.presentation",
                "application/vnd.ms-excel",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.shee",
                "application/vnd.oasis.opendocument.spreadsheet",
                "application/x-download",
                "application/octet-stream",
                "application/msword",
                "application/vnd.oasis.opendocument.text",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "application/json",
                "application/tei+xml",
                "application/rtf",
                "application/xhtml+xml",
                "image/gif",
                "image/jpeg",
                "image/pjpeg",
                "image/png",
                "image/tiff",
                "image/vnd.microsoft.icon",
                "image/svg+xml",
                "text/html",
                "text/plain",
                "text/rtf",
                "text/x-conll",
                "text/xml"
            ],
            "languages": [ "afr", "ara", "ast", "bel", "bos", "bre", "bul", "cat", "ces", "chu", "cop", "cos", "cym", "dan", "deu", "ell", "eng", "epo", "est", "eus", "fao", "fas", "fin", "fra", "gla", "gle", "glg", "glv", "gml", "got", "hat", "heb", "hin", "hrv", "hun", "hye", "iku", "ind", "isl", "ita", "jav", "jpn", "kan", "kat", "kor", "kur", "lat", "lav", "lit", "ltz", "mal", "mar", "mkd", "mlt", "msa", "nld", "nno", "nob", "nor", "oci", "pol", "por", "ron", "rus", "slk", "slv", "sme", "spa", "sqi", "srp", "swa", "swe", "tam", "tel", "tur", "uig", "ukr", "urd", "uzb", "vie", "wol", "yid", "zho" ],
            "maxSize": 40960000,
            "multiple": true
        }
    ],
    "webApplication": {
        "url": "https://cst.dk/texton/specifyGoal",
        "queryParameters": [
            {
                "name": "URLS",
                "bind": "text/dataurl"
            },
            {
                "name": "Ilang",
                "bind": "text/language",
                "encoding": "639-3"
            },
            {
                "name": "Olang",
                "bind": "text/language",
                "encoding": "639-3"
            },
            {
                "name": "UIlanguage",
                "value": "en"
            },
            {
                "name": "Ifacet",
                "value": "txt"
            },
            {
                "name": "Iambig",
                "value": "una"
            },
            {
                "name": "Iapp",
                "value": "nrm"
            }
        ]
    }
}

=== clarin-eric/switchboard-tool-registry/tools/spaCy NEL.json
{
	"formatVersion": "2",
    "id": 122123,
    "task": "Named Entity Recognition",
    "deployment": "production",
    "integrationType" : "Integrated",
    "name": "spaCy NEL",
    "logo": "It-Sr-NER-logo-small.png",
    "homepage": "https://github.com/rankastankovic/It-Sr-NER",
    "location": "Belgrade, Serbia",
    "creators": "Universit√† degli studi di Torino",
    "contact": {
        "person": "Olja Perisic",
        "email": "olja.perisic@unito.it"
    },
    "authentication": "no",
    "description": "language-independent NEL web service for texts and files (txt).",
    
    "webApplication" : {
		"url": "https://ners.jerteh.rs/api",
    	"queryParameters": [{ 
          		"name": "feat",
			"value": "nel"
       	}, {
          		"name": "data",
			"bind": "file/dataurl",
			"encoding": "639-1"
        }]
          
       
    },
    

     "inputs" : [{
        "id": "file",
        "mediatypes": ["text/plain"]
     }]
      
}

=== clarin-eric/switchboard-tool-registry/tools/spaCy bilingual NEL.json
{
	"formatVersion": "2",
    "id": 122127,
    "task": "Named Entity Recognition",
    "deployment": "production",
    "integrationType" : "Integrated",
    "name": "spaCy bilingual NEL (for TMX)",
    "logo": "It-Sr-NER-logo-small.png",
    "homepage": "https://github.com/rankastankovic/It-Sr-NER",
    "location": "Belgrade, Serbia",
    "creators": "Universit√† degli studi di Torino",
    "contact": {
        "person": "Olja Perisic",
        "email": "olja.perisic@unito.it"
    },
    "authentication": "no",
    "description": "NEL web service for parallel texts (tmx).",
    
    "webApplication" : {
		"url": "https://ners.jerteh.rs/api",
    	"queryParameters": [{
			"name": "lng",
			"bind": "file/language",
			"encoding": "639-1"
        }, { 
          		"name": "feat",
			"value": "nel"
       	}, {
          		"name": "data",
			"bind": "file/dataurl",
			"encoding": "639-1"
        }]
          
       
    },
    

     "inputs" : [{
        "id": "file",
        "mediatypes": ["application/xml"]
     }]
      
}

=== clarin-eric/switchboard-tool-registry/tools/MultiEmo.json
{
    "formatVersion": "2",
    "id": 139,
    "task": "Sentiment Analysis",
    "deployment": "production",
    "integrationType": "Integrated",
    "name": "MultiEmo",
    "description": "Tool for the multilingual sentiment analysis of texts.",
    "logo": "clarin-pl.png",
    "homepage": "https://services.clarin-pl.eu/services/multiemo",
    "creators": "Clarin-PL",
    "contact": {
        "person": "Tomasz Walkowiak",
        "email": "tomasz.walkowiak@pwr.edu.pl"
    },
    "keywords": ["topic", "topic modelling", "LDA", "text analysis"],
    "location": "Wroclaw, Poland",
    "authentication": "Yes, user should create an account on the Clarin-PL website",
    "inputs": [{
        "id": "text",
        "mediatypes": ["application/zip"],
        "languages": ["eng", "pol", "deu", "spa", "fra", "ita", "nld", "por", "rus", "jpn"]
    }],
    "webApplication": {
        "url": "https://services.clarin-pl.eu/services/multiemo/creator",
        "queryParameters": [{
            "name": "weblicht-input",
            "bind": "text/dataurl"
        }]
    }
}

=== clarin-eric/switchboard-tool-registry/tools/Keytool.json
{
    "formatVersion": "2",
    "id": 88,
    "task": "Keyword Extractor",
    "deployment": "production",
    "integrationType": "Integrated",
    "name": "Keytool",
    "description": "Service integrates several keyword determination methods, including generative models and multi-label classification. The combination of several advanced techniques makes the results more reliable and accurate.",
    "logo": "clarin-pl.png",
    "homepage": "https://services.clarin-pl.eu/services/keytool",
    "creators": "Clarin-PL",
    "contact": {
        "person": "Tomasz Walkowiak",
        "email": "tomasz.walkowiak@pwr.edu.pl"
    },
    "keywords": ["keyword extraction", "keyword determination"],
    "location": "Wroclaw, Poland",
    "authentication": "Yes, user should create an account on the Clarin-PL website",
    "inputs": [{
        "id": "text",
        "mediatypes": ["application/zip"],
        "languages": ["eng", "pol"]
    }],
    "webApplication": {
        "url": "https://services.clarin-pl.eu/services/keytool/creator",
        "queryParameters": [{
            "name": "weblicht-input",
            "bind": "text/dataurl"
        }]
    }
}

=== clarin-eric/switchboard-tool-registry/tools/AspectEmo.json
{
    "formatVersion": "2",
    "id": 56,
    "task": "Sentiment Analysis",
    "deployment": "production",
    "integrationType": "Integrated",
    "name": "AspectEmo",
    "description": "AspectEmo operates on the sound of individual words. This allows it to recognize nuanced or contrasting opinions within a single sentence or text, rather than providing an overall rating for an entire segment.",
    "logo": "clarin-pl.png",
    "homepage": "https://services.clarin-pl.eu/services/aspectemo",
    "creators": "Clarin-PL",
    "contact": {
        "person": "Tomasz Walkowiak",
        "email": "tomasz.walkowiak@pwr.edu.pl"
    },
    "keywords": ["sentiment analysis", "opinion mining", "aspect-based sentiment analysis", "emotion detection", "aspect detection"],
    "location": "Wroclaw, Poland",
    "authentication": "Yes, user should create an account on the Clarin-PL website",
    "inputs": [{
        "id": "text",
        "mediatypes": ["application/zip"],
        "languages": ["eng", "pol"]
    }],
    "webApplication": {
        "url": "https://services.clarin-pl.eu/services/aspectemo/creator",
        "queryParameters": [{
            "name": "weblicht-input",
            "bind": "text/dataurl"
        }]
    }
}
